-- Active: 1671688949427@@127.0.0.1@3308@db_optimised
CREATE TABLE `student` (ID INT,NAME Varchar(20), DOB date);
CREATE TABLE `Student_phone`(ID INT, phone_number varchar(20));

INSERT INTO `student` values (101,"Rahul",'1999-4-3'),(102,'Mukul','2000-3-6');
INSERT INTO `student_phone` VALUES (101,'64364545'),(101,'345543533');
SELECT * FROM `student`;

-- Age
SELECT *, TIMESTAMPDIFF(YEAR, DOB,CURDATE()) 'AGE' FROM student;
CREATE VIEW Student_age AS SELECT ID,NAME, TIMESTAMPDIFF(YEAR, DOB,CURDATE()) 'AGE' FROM student;

Show tables;

desc student_age;
alter table student ADD (Street Varchar(20), CITY VARCHAR(20), Pincode Numeric(6));
UPDATE student SET street="1st main", city='Bangalore', PINCODE= 565415 WHERE id=101;

SELECT Name, CONCAT(STREET,',', CITY,',', PINCODE) 'ADDRESS' FROM student;
CREATE VIEW student_address_view AS SELECT id,name, CONCAT(STREET,',', CITY,',', PINCODE) 'ADDRESS' FROM student;

SELECT * FROM student_address_view;

--============================================

--NORMALIZATION

CREATE TABLE CUSTOMER(CUSTID INT PRIMARY KEY,CNAME VARCHAR(25),CLOC VARCHAR(15));
DROP TABLE INV_CUST;

CREATE TABLE IF NOT EXISTS INV_CUST(INVNO INT PRIMARY KEY, CUSTID INT, 
                        CONSTRAINT `FK_CUST_INVCUST` FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID)
                        );
ALTER TABLE  INV_CUST ADD CONSTRAINT `FK_CUST_INVCUST` FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID);

CREATE TABLE INV_ITEM (INVNO INT, SLNO INT, ITEM VARCHAR(15), QTY SMALLINT,TOTAL INT,
                        FOREIGN KEY (INV) REFERENCES);

ALTER TABLE INV_ITEM ADD PRIMARY KEY (INVNO,SLNO);
ALTER TABLE INV_ITEM ADD CONSTRAINT `FK_INVCUST_INVITEM` FOREIGN KEY (INVNO) REFERENCES INV_CUST(INVNO);

INSERT INTO CUSTOMER VALUES (11,'XYZ','HYD'),(22,'ABC','BLR');
INSERT INTO INV_CUST VALUES(5001,11),(5002,22),(5003,11);
INSERT INTO INV_ITEM VALUES (5001,1,'TFT',10,10000);


